ALTER TABLE "articles"
ADD COLUMN "imageFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "imageFocalY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "imageFilter" TEXT NOT NULL DEFAULT 'GRAYSCALE';

ALTER TABLE "lessons"
ADD COLUMN "imageFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "imageFocalY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "imageFilter" TEXT NOT NULL DEFAULT 'GRAYSCALE';
